### ISSUE TITLE
No 404 page?

### ISSUE THREAD

**Issue by richb-hanover** [cloudmu/react-redux-starter-kit#12]
When I enter a URL of `localhost:3000/nothing-there`, I get back to the Home page without any indication of a "page not found".

Is this expected?

**Update:** the URL gets re-written to `http://localhost:3000/nothing-there#/?_k=cnn950`

**Comment by cloudmu** [comment]
I use hashHistory just to avoid setting up the demo server (required to serve index.html for browserHistory).  I suggest you use browserHistory instead of hashHistory, which involves some simple code changes. See [react-router doc](https://github.com/reactjs/react-router/blob/master/docs/guides/Histories.md#browserhistory)

To test 404 page with hashHistory, remember to use "#":
`localhost:3000/#/nothing-there`
