### ISSUE TITLE
Fetching Quotes with API Middleware

### ISSUE THREAD

**Issue by tarkanlar** [cloudmu/react-redux-starter-kit#4]
It would be really great if there would be an example and a middleware as explained here.
https://auth0.com/blog/2016/01/04/secure-your-react-and-redux-app-with-jwt-authentication/

**Comment by cloudmu** [comment]
The JWT based authentication on client side is implemented based on redux (with its actions and reducers). The async calls to the backend server for authentication is indeed done with thunk middleware.  What's missing is to include the jwt token in authorization header in subsequent server API calls, so that the server can authenticate (i.e. validate the token signature).  
(See #8)

**Comment by cloudmu** [comment]
JWT based API server is added back, thanks to the latest create-react-app feature [Proxying API Requests](https://github.com/facebookincubator/create-react-app/blob/ef94b0561d5afb9b50b905fa5cd3f94e965c69c0/template/README.md#proxying-api-requests-in-development)
