### ISSUE TITLE
Isomorphic (Universal) feature

### ISSUE THREAD

**Issue by chosenvictim** [cloudmu/react-redux-starter-kit#7]
Nice work. It would be more nice if you could do Server Side rendering with Koa and react-router. I would love to see it in your repo because i really like your code structure and I am using this repo as a reference to my pet project.

**Comment by cloudmu** [comment]
@shek8034 Thanks.  I agree server side rendering would be great in general.  But in this case client only rendering is intentional.  This repo serves as a playground for my actual work which uses Java instead of node.js as back-end.  You may want to check out react-redux-universal-hot-example by @erikras

**Comment by richb-hanover** [comment]
Regrettably, erikras' react-redux-universal-hot-example has stalled. See https://github.com/erikras/react-redux-universal-hot-example/issues/1184
